# Generated by Django 5.2.8 on 2025-12-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_todolist_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='taskId',
            field=models.IntegerField(default=0),
        ),
    ]
