# Generated by Django 5.2.8 on 2025-12-14 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_taskid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='taskDueDate',
            field=models.DateField(default=datetime.date(2025, 12, 14)),
        ),
    ]
